export const kanjidb = [
  {
    id: 1,
    kanji: "	一	",
    meaning: "	one	",
    onYomi: "	ichi, itsu	",
    kunYomi: "	hito-tsu	",
    grade: 1,
  },
  {
    id: 2,
    kanji: "	二	",
    meaning: "	two	",
    onYomi: "	ni, ji	",
    kunYomi: "	futa-tsu	",
    grade: 1,
  },
  {
    id: 3,
    kanji: "	三	",
    meaning: "	three	",
    onYomi: "	san	",
    kunYomi: "	mit-tsu	",
    grade: 1,
  },
  {
    id: 4,
    kanji: "	四	",
    meaning: "	four	",
    onYomi: "	shi	",
    kunYomi: "	yot-tsu, yon	",
    grade: 1,
  },
  {
    id: 5,
    kanji: "	五	",
    meaning: "	five	",
    onYomi: "	go	",
    kunYomi: "	itsu-tsu	",
    grade: 1,
  },
  {
    id: 6,
    kanji: "	六	",
    meaning: "	six	",
    onYomi: "	roku	",
    kunYomi: "	mut-tsu	",
    grade: 1,
  },
  {
    id: 7,
    kanji: "	七	",
    meaning: "	seven	",
    onYomi: "	shichi	",
    kunYomi: "	nana-tsu, nana	",
    grade: 1,
  },
  {
    id: 8,
    kanji: "	八	",
    meaning: "	eight	",
    onYomi: "	hachi	",
    kunYomi: "	yat-tsu	",
    grade: 1,
  },
  {
    id: 9,
    kanji: "	九	",
    meaning: "	nine	",
    onYomi: "	ku, kyū	",
    kunYomi: "	kokono-tsu	",
    grade: 1,
  },
  {
    id: 10,
    kanji: "	十	",
    meaning: "	ten	",
    onYomi: "	jū	",
    kunYomi: "	tō	",
    grade: 1,
  },
  {
    id: 11,
    kanji: "	百	",
    meaning: "	hundred	",
    onYomi: "	hyaku	",
    kunYomi: "	momo	",
    grade: 1,
  },
  {
    id: 12,
    kanji: "	千	",
    meaning: "	thousand	",
    onYomi: "	sen	",
    kunYomi: "	chi	",
    grade: 1,
  },
  {
    id: 13,
    kanji: "	上	",
    meaning: "	top, above	",
    onYomi: "	jō	",
    kunYomi: "	ue	",
    grade: 1,
  },
  {
    id: 14,
    kanji: "	下	",
    meaning: "	bottom, below	",
    onYomi: "	ka, ge	",
    kunYomi: "	shita, shimo, moto	",
    grade: 1,
  },
  {
    id: 15,
    kanji: "	左	",
    meaning: "	left	",
    onYomi: "	sa	",
    kunYomi: "	hidari	",
    grade: 1,
  },
  {
    id: 16,
    kanji: "	右	",
    meaning: "	right	",
    onYomi: "	u, yū	",
    kunYomi: "	migi	",
    grade: 1,
  },
  {
    id: 17,
    kanji: "	中	",
    meaning: "	inside, middle	",
    onYomi: "	chū, jū	",
    kunYomi: "	naka	",
    grade: 1,
  },
  {
    id: 18,
    kanji: "	大	",
    meaning: "	large	",
    onYomi: "	dai, tai	",
    kunYomi: "	ō-kii, ō	",
    grade: 1,
  },
  {
    id: 19,
    kanji: "	小	",
    meaning: "	small	",
    onYomi: "	shō	",
    kunYomi: "	chii-sai, ko, o	",
    grade: 1,
  },
  {
    id: 20,
    kanji: "	月	",
    meaning: "	month, moon	",
    onYomi: "	gatsu, getsu	",
    kunYomi: "	tsuki	",
    grade: 1,
  },
  {
    id: 21,
    kanji: "	日	",
    meaning: "	day, sun	",
    onYomi: "	nichi, jitsu	",
    kunYomi: "	hi, ka	",
    grade: 1,
  },
  {
    id: 22,
    kanji: "	年	",
    meaning: "	year	",
    onYomi: "	nen	",
    kunYomi: "	toshi	",
    grade: 1,
  },
  {
    id: 23,
    kanji: "	早	",
    meaning: "	early	",
    onYomi: "	sō, sa	",
    kunYomi: "	haya-i	",
    grade: 1,
  },
  {
    id: 24,
    kanji: "	木	",
    meaning: "	tree	",
    onYomi: "	moku, boku	",
    kunYomi: "	ki	",
    grade: 1,
  },
  {
    id: 25,
    kanji: "	林	",
    meaning: "	woods	",
    onYomi: "	rin	",
    kunYomi: "	hayashi	",
    grade: 1,
  },
  {
    id: 26,
    kanji: "	山	",
    meaning: "	mountain	",
    onYomi: "	san	",
    kunYomi: "	yama	",
    grade: 1,
  },
  {
    id: 27,
    kanji: "	川	",
    meaning: "	river	",
    onYomi: "	sen	",
    kunYomi: "	kawa	",
    grade: 1,
  },
  {
    id: 28,
    kanji: "	土	",
    meaning: "	soil	",
    onYomi: "	to, do	",
    kunYomi: "	tsuchi	",
    grade: 1,
  },
  {
    id: 29,
    kanji: "	空	",
    meaning: "	sky	",
    onYomi: "	kū	",
    kunYomi: "	sora, a-ku, kara	",
    grade: 1,
  },
  {
    id: 30,
    kanji: "	田	",
    meaning: "	rice field	",
    onYomi: "	den	",
    kunYomi: "	da, ta	",
    grade: 1,
  },
  {
    id: 31,
    kanji: "	天	",
    meaning: "	heaven, sky	",
    onYomi: "	ten	",
    kunYomi: "	ame, ama	",
    grade: 1,
  },
  {
    id: 32,
    kanji: "	生	",
    meaning: "	living, birth, raw	",
    onYomi: "	sei, shō	",
    kunYomi: "	i-kiru, u-mu, nama	",
    grade: 1,
  },
  {
    id: 33,
    kanji: "	花	",
    meaning: "	flower	",
    onYomi: "	ka	",
    kunYomi: "	hana	",
    grade: 1,
  },
  {
    id: 34,
    kanji: "	草	",
    meaning: "	grass	",
    onYomi: "	sō	",
    kunYomi: "	kusa	",
    grade: 1,
  },
  {
    id: 35,
    kanji: "	虫	",
    meaning: "	insect	",
    onYomi: "	chū	",
    kunYomi: "	mushi	",
    grade: 1,
  },
  {
    id: 36,
    kanji: "	犬	",
    meaning: "	dog	",
    onYomi: "	ken	",
    kunYomi: "	inu	",
    grade: 1,
  },
  {
    id: 37,
    kanji: "	人	",
    meaning: "	person	",
    onYomi: "	jin, nin	",
    kunYomi: "	hito	",
    grade: 1,
  },
  {
    id: 38,
    kanji: "	名	",
    meaning: "	name	",
    onYomi: "	mei, myō	",
    kunYomi: "	na	",
    grade: 1,
  },
  {
    id: 39,
    kanji: "	女	",
    meaning: "	female	",
    onYomi: "	jo, nyo	",
    kunYomi: "	on'na	",
    grade: 1,
  },
  {
    id: 40,
    kanji: "	男	",
    meaning: "	male	",
    onYomi: "	dan, nan	",
    kunYomi: "	otoko	",
    grade: 1,
  },
  {
    id: 41,
    kanji: "	子	",
    meaning: "	child	",
    onYomi: "	shi, su	",
    kunYomi: "	ko	",
    grade: 1,
  },
  {
    id: 42,
    kanji: "	目	",
    meaning: "	eye	",
    onYomi: "	moku	",
    kunYomi: "	me	",
    grade: 1,
  },
  {
    id: 43,
    kanji: "	耳	",
    meaning: "	ear	",
    onYomi: "	ji, ni	",
    kunYomi: "	mimi	",
    grade: 1,
  },
  {
    id: 44,
    kanji: "	口	",
    meaning: "	mouth	",
    onYomi: "	kō	",
    kunYomi: "	kuchi	",
    grade: 1,
  },
  {
    id: 45,
    kanji: "	手	",
    meaning: "	hand	",
    onYomi: "	shu	",
    kunYomi: "	te	",
    grade: 1,
  },
  {
    id: 46,
    kanji: "	足	",
    meaning: "	foot, suffice	",
    onYomi: "	soku	",
    kunYomi: "	ashi, ta-riru	",
    grade: 1,
  },
  {
    id: 47,
    kanji: "	見	",
    meaning: "	see	",
    onYomi: "	ken, gen	",
    kunYomi: "	mi-ru	",
    grade: 1,
  },
  {
    id: 48,
    kanji: "	音	",
    meaning: "	sound	",
    onYomi: "	on	",
    kunYomi: "	ne, oto	",
    grade: 1,
  },
  {
    id: 49,
    kanji: "	力	",
    meaning: "	power	",
    onYomi: "	riki, ryoku	",
    kunYomi: "	chikara	",
    grade: 1,
  },
  {
    id: 50,
    kanji: "	気	",
    meaning: "	spirit, air	",
    onYomi: "	ki, ke	",
    kunYomi: "	iki	",
    grade: 1,
  },
  {
    id: 51,
    kanji: "	円	",
    meaning: "	yen, circle	",
    onYomi: "	en	",
    kunYomi: "	maru	",
    grade: 1,
  },
  {
    id: 52,
    kanji: "	入	",
    meaning: "	enter	",
    onYomi: "	nyū	",
    kunYomi: "	hai-ru, i-ru	",
    grade: 1,
  },
  {
    id: 53,
    kanji: "	出	",
    meaning: "	exit	",
    onYomi: "	shutsu	",
    kunYomi: "	de-ru	",
    grade: 1,
  },
  {
    id: 54,
    kanji: "	立	",
    meaning: "	stand up	",
    onYomi: "	ritsu	",
    kunYomi: "	ta-tsu	",
    grade: 1,
  },
  {
    id: 55,
    kanji: "	休	",
    meaning: "	rest	",
    onYomi: "	kyū	",
    kunYomi: "	yasu-mu	",
    grade: 1,
  },
  {
    id: 56,
    kanji: "	先	",
    meaning: "	previous	",
    onYomi: "	sen	",
    kunYomi: "	saki	",
    grade: 1,
  },
  {
    id: 57,
    kanji: "	夕	",
    meaning: "	evening	",
    onYomi: "	seki	",
    kunYomi: "	yū	",
    grade: 1,
  },
  {
    id: 58,
    kanji: "	本	",
    meaning: "	book	",
    onYomi: "	hon	",
    kunYomi: "	moto	",
    grade: 1,
  },
  {
    id: 59,
    kanji: "	文	",
    meaning: "	text	",
    onYomi: "	bun, mon	",
    kunYomi: "	fumi	",
    grade: 1,
  },
  {
    id: 60,
    kanji: "	字	",
    meaning: "	character	",
    onYomi: "	ji	",
    kunYomi: "	aza	",
    grade: 1,
  },
  {
    id: 61,
    kanji: "	学	",
    meaning: "	study	",
    onYomi: "	gaku	",
    kunYomi: "	mana-bu	",
    grade: 1,
  },
  {
    id: 62,
    kanji: "	校	",
    meaning: "	school	",
    onYomi: "	kō	",
    kunYomi: "	kase	",
    grade: 1,
  },
  {
    id: 63,
    kanji: "	村	",
    meaning: "	village	",
    onYomi: "	son	",
    kunYomi: "	mura	",
    grade: 1,
  },
  {
    id: 64,
    kanji: "	町	",
    meaning: "	town	",
    onYomi: "	chō	",
    kunYomi: "	machi	",
    grade: 1,
  },
  {
    id: 65,
    kanji: "	森	",
    meaning: "	forest	",
    onYomi: "	shin	",
    kunYomi: "	mori	",
    grade: 1,
  },
  {
    id: 66,
    kanji: "	正	",
    meaning: "	correct	",
    onYomi: "	sei, shō	",
    kunYomi: "	tada-shii, masa	",
    grade: 1,
  },
  {
    id: 67,
    kanji: "	水	",
    meaning: "	water	",
    onYomi: "	sui	",
    kunYomi: "	mizu	",
    grade: 1,
  },
  {
    id: 68,
    kanji: "	火	",
    meaning: "	fire	",
    onYomi: "	ka	",
    kunYomi: "	hi	",
    grade: 1,
  },
  {
    id: 69,
    kanji: "	玉	",
    meaning: "	jewel, ball	",
    onYomi: "	gyoku	",
    kunYomi: "	tama	",
    grade: 1,
  },
  {
    id: 70,
    kanji: "	王	",
    meaning: "	king	",
    onYomi: "	ō	",
    kunYomi: "	kimi	",
    grade: 1,
  },
  {
    id: 71,
    kanji: "	石	",
    meaning: "	stone	",
    onYomi: "	seki, koku	",
    kunYomi: "	ishi	",
    grade: 1,
  },
  {
    id: 72,
    kanji: "	竹	",
    meaning: "	bamboo	",
    onYomi: "	chiku	",
    kunYomi: "	take	",
    grade: 1,
  },
  {
    id: 73,
    kanji: "	糸	",
    meaning: "	thread	",
    onYomi: "	shi	",
    kunYomi: "	ito	",
    grade: 1,
  },
  {
    id: 74,
    kanji: "	貝	",
    meaning: "	shellfish	",
    onYomi: "	bai	",
    kunYomi: "	kai	",
    grade: 1,
  },
  {
    id: 75,
    kanji: "	車	",
    meaning: "	vehicle	",
    onYomi: "	sha	",
    kunYomi: "	kuruma	",
    grade: 1,
  },
  {
    id: 76,
    kanji: "	金	",
    meaning: "	gold, money	",
    onYomi: "	kin	",
    kunYomi: "	kane, kana	",
    grade: 1,
  },
  {
    id: 77,
    kanji: "	雨	",
    meaning: "	rain	",
    onYomi: "	u	",
    kunYomi: "	ame, ama	",
    grade: 1,
  },
  {
    id: 78,
    kanji: "	赤	",
    meaning: "	red	",
    onYomi: "	seki	",
    kunYomi: "	aka	",
    grade: 1,
  },
  {
    id: 79,
    kanji: "	青	",
    meaning: "	blue	",
    onYomi: "	sei, shō	",
    kunYomi: "	ao	",
    grade: 1,
  },
  {
    id: 80,
    kanji: "	白	",
    meaning: "	white	",
    onYomi: "	haku	",
    kunYomi: "	shiro, shira	",
    grade: 1,
  },
];
