export const kanjidb = [
  {
    id: 1,
    kanji: "	一	",
    meaning: "	one	",
    onYomi: "	ichi, itsu	",
    kunYomi: "	hito-tsu	",
    grade: 1,
  },
  {
    id: 2,
    kanji: "	二	",
    meaning: "	two	",
    onYomi: "	ni, ji	",
    kunYomi: "	futa-tsu	",
    grade: 1,
  },
  {
    id: 3,
    kanji: "	三	",
    meaning: "	three	",
    onYomi: "	san	",
    kunYomi: "	mit-tsu	",
    grade: 1,
  },
  {
    id: 4,
    kanji: "	四	",
    meaning: "	four	",
    onYomi: "	shi	",
    kunYomi: "	yot-tsu, yon	",
    grade: 1,
  },
  {
    id: 5,
    kanji: "	五	",
    meaning: "	five	",
    onYomi: "	go	",
    kunYomi: "	itsu-tsu	",
    grade: 1,
  },
  {
    id: 6,
    kanji: "	六	",
    meaning: "	six	",
    onYomi: "	roku	",
    kunYomi: "	mut-tsu	",
    grade: 1,
  },
  {
    id: 7,
    kanji: "	七	",
    meaning: "	seven	",
    onYomi: "	shichi	",
    kunYomi: "	nana-tsu, nana	",
    grade: 1,
  },
  {
    id: 8,
    kanji: "	八	",
    meaning: "	eight	",
    onYomi: "	hachi	",
    kunYomi: "	yat-tsu	",
    grade: 1,
  },
  {
    id: 9,
    kanji: "	九	",
    meaning: "	nine	",
    onYomi: "	ku, kyū	",
    kunYomi: "	kokono-tsu	",
    grade: 1,
  },
  {
    id: 10,
    kanji: "	十	",
    meaning: "	ten	",
    onYomi: "	jū	",
    kunYomi: "	tō	",
    grade: 1,
  },
  {
    id: 11,
    kanji: "	百	",
    meaning: "	hundred	",
    onYomi: "	hyaku	",
    kunYomi: "	momo	",
    grade: 1,
  },
  {
    id: 12,
    kanji: "	千	",
    meaning: "	thousand	",
    onYomi: "	sen	",
    kunYomi: "	chi	",
    grade: 1,
  },
];
