export const kanjidb = [
  {
    id: 81,
    kanji: "	数	",
    meaning: "	number, count	",
    onYomi: "	sū	",
    kunYomi: "	kazu	",
    grade: 2,
  },
  {
    id: 82,
    kanji: "	多	",
    meaning: "	many, much	",
    onYomi: "	ta	",
    kunYomi: "	oo-i	",
    grade: 2,
  },
  {
    id: 83,
    kanji: "	少	",
    meaning: "	a few, a little	",
    onYomi: "	shō	",
    kunYomi: "	suku-nai, suko-shi	",
    grade: 2,
  },
  {
    id: 84,
    kanji: "	万	",
    meaning: "	ten thousand	",
    onYomi: "	ban, man	",
    kunYomi: "	yorozu	",
    grade: 2,
  },
  {
    id: 85,
    kanji: "	半	",
    meaning: "	half	",
    onYomi: "	han	",
    kunYomi: "	naka-ba	",
    grade: 2,
  },
  {
    id: 86,
    kanji: "	形	",
    meaning: "	shape	",
    onYomi: "	kei, gyō	",
    kunYomi: "	katachi	",
    grade: 2,
  },
  {
    id: 87,
    kanji: "	太	",
    meaning: "	thick	",
    onYomi: "	ta	",
    kunYomi: "	futo-i	",
    grade: 2,
  },
  {
    id: 88,
    kanji: "	細	",
    meaning: "	thin	",
    onYomi: "	sai	",
    kunYomi: "	hoso-i	",
    grade: 2,
  },
  {
    id: 89,
    kanji: "	広	",
    meaning: "	wide	",
    onYomi: "	kō	",
    kunYomi: "	hiro-i	",
    grade: 2,
  },
  {
    id: 90,
    kanji: "	長	",
    meaning: "	long, leader	",
    onYomi: "	chō	",
    kunYomi: "	naga-i	",
    grade: 2,
  },
  {
    id: 91,
    kanji: "	点	",
    meaning: "	point	",
    onYomi: "	ten	",
    kunYomi: "	bochi	",
    grade: 2,
  },
  {
    id: 92,
    kanji: "	丸	",
    meaning: "	circle	",
    onYomi: "	gan	",
    kunYomi: "	maru	",
    grade: 2,
  },
  {
    id: 93,
    kanji: "	交	",
    meaning: "	intersect	",
    onYomi: "	kō	",
    kunYomi: "	maji-waru	",
    grade: 2,
  },
  {
    id: 94,
    kanji: "	光	",
    meaning: "	light	",
    onYomi: "	kō	",
    kunYomi: "	hikari	",
    grade: 2,
  },
  {
    id: 95,
    kanji: "	角	",
    meaning: "	corner, horn	",
    onYomi: "	kaku	",
    kunYomi: "	kado, tsuno, sumi	",
    grade: 2,
  },
  {
    id: 96,
    kanji: "	計	",
    meaning: "	measure	",
    onYomi: "	kei	",
    kunYomi: "	haka-ru	",
    grade: 2,
  },
  {
    id: 97,
    kanji: "	直	",
    meaning: "	straight, fix	",
    onYomi: "	choku, jiki	",
    kunYomi: "	tada-chini, nao-su	",
    grade: 2,
  },
  {
    id: 98,
    kanji: "	線	",
    meaning: "	line	",
    onYomi: "	sen	",
    kunYomi: "	suji	",
    grade: 2,
  },
  {
    id: 99,
    kanji: "	矢	",
    meaning: "	arrow	",
    onYomi: "	shi	",
    kunYomi: "	ya	",
    grade: 2,
  },
  {
    id: 100,
    kanji: "	弱	",
    meaning: "	weak	",
    onYomi: "	jaku	",
    kunYomi: "	yowa-i	",
    grade: 2,
  },
  {
    id: 101,
    kanji: "	強	",
    meaning: "	strong	",
    onYomi: "	kyō	",
    kunYomi: "	tsuyo-i	",
    grade: 2,
  },
  {
    id: 102,
    kanji: "	高	",
    meaning: "	high	",
    onYomi: "	kō	",
    kunYomi: "	taka-i	",
    grade: 2,
  },
  {
    id: 103,
    kanji: "	同	",
    meaning: "	same	",
    onYomi: "	dō	",
    kunYomi: "	ona-ji	",
    grade: 2,
  },
  {
    id: 104,
    kanji: "	親	",
    meaning: "	parent	",
    onYomi: "	shin	",
    kunYomi: "	oya	",
    grade: 2,
  },
  {
    id: 105,
    kanji: "	母	",
    meaning: "	mother	",
    onYomi: "	bo	",
    kunYomi: "	haha, kā	",
    grade: 2,
  },
  {
    id: 106,
    kanji: "	父	",
    meaning: "	father	",
    onYomi: "	fu	",
    kunYomi: "	chichi, tou	",
    grade: 2,
  },
  {
    id: 107,
    kanji: "	姉	",
    meaning: "	older sister	",
    onYomi: "	shi	",
    kunYomi: "	ane	",
    grade: 2,
  },
  {
    id: 108,
    kanji: "	兄	",
    meaning: "	older brother	",
    onYomi: "	kei, kyō	",
    kunYomi: "	ani	",
    grade: 2,
  },
  {
    id: 109,
    kanji: "	弟	",
    meaning: "	younger brother	",
    onYomi: "	tei, dai	",
    kunYomi: "	otōto	",
    grade: 2,
  },
  {
    id: 110,
    kanji: "	妹	",
    meaning: "	younger sister	",
    onYomi: "	mai	",
    kunYomi: "	imōto	",
    grade: 2,
  },
  {
    id: 111,
    kanji: "	自	",
    meaning: "	oneself	",
    onYomi: "	ji, shi	",
    kunYomi: "	mizuka-ra	",
    grade: 2,
  },
  {
    id: 112,
    kanji: "	友	",
    meaning: "	friend	",
    onYomi: "	yū	",
    kunYomi: "	tomo	",
    grade: 2,
  },
  {
    id: 113,
    kanji: "	体	",
    meaning: "	body	",
    onYomi: "	tai	",
    kunYomi: "	karada	",
    grade: 2,
  },
  {
    id: 114,
    kanji: "	毛	",
    meaning: "	hair	",
    onYomi: "	mō	",
    kunYomi: "	ke	",
    grade: 2,
  },
  {
    id: 115,
    kanji: "	頭	",
    meaning: "	head	",
    onYomi: "	tō	",
    kunYomi: "	atama	",
    grade: 2,
  },
  {
    id: 116,
    kanji: "	顔	",
    meaning: "	face	",
    onYomi: "	gan	",
    kunYomi: "	kao	",
    grade: 2,
  },
  {
    id: 117,
    kanji: "	首	",
    meaning: "	neck	",
    onYomi: "	shu	",
    kunYomi: "	kubi	",
    grade: 2,
  },
  {
    id: 118,
    kanji: "	心	",
    meaning: "	heart	",
    onYomi: "	shin	",
    kunYomi: "	kokoro	",
    grade: 2,
  },
  {
    id: 119,
    kanji: "	時	",
    meaning: "	time	",
    onYomi: "	ji	",
    kunYomi: "	toki	",
    grade: 2,
  },
  {
    id: 120,
    kanji: "	曜	",
    meaning: "	day of the week	",
    onYomi: "	yō	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 121,
    kanji: "	朝	",
    meaning: "	morning	",
    onYomi: "	chō	",
    kunYomi: "	asa	",
    grade: 2,
  },
  {
    id: 122,
    kanji: "	昼	",
    meaning: "	daytime	",
    onYomi: "	chū	",
    kunYomi: "	hiru	",
    grade: 2,
  },
  {
    id: 123,
    kanji: "	夜	",
    meaning: "	night	",
    onYomi: "	ya	",
    kunYomi: "	yoru	",
    grade: 2,
  },
  {
    id: 124,
    kanji: "	分	",
    meaning: "	minute, understand	",
    onYomi: "	fun, bun	",
    kunYomi: "	wa-karu	",
    grade: 2,
  },
  {
    id: 125,
    kanji: "	週	",
    meaning: "	week	",
    onYomi: "	shū	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 126,
    kanji: "	春	",
    meaning: "	spring	",
    onYomi: "	shun	",
    kunYomi: "	haru	",
    grade: 2,
  },
  {
    id: 127,
    kanji: "	夏	",
    meaning: "	summer	",
    onYomi: "	ka	",
    kunYomi: "	natsu	",
    grade: 2,
  },
  {
    id: 128,
    kanji: "	秋	",
    meaning: "	autumn	",
    onYomi: "	shū	",
    kunYomi: "	aki	",
    grade: 2,
  },
  {
    id: 129,
    kanji: "	冬	",
    meaning: "	winter	",
    onYomi: "	tō	",
    kunYomi: "	fuyu	",
    grade: 2,
  },
  {
    id: 130,
    kanji: "	今	",
    meaning: "	now	",
    onYomi: "	kon	",
    kunYomi: "	ima	",
    grade: 2,
  },
  {
    id: 131,
    kanji: "	新	",
    meaning: "	new	",
    onYomi: "	shin	",
    kunYomi: "	atara-shii, ara-ta	",
    grade: 2,
  },
  {
    id: 132,
    kanji: "	古	",
    meaning: "	old	",
    onYomi: "	ko	",
    kunYomi: "	furu-i	",
    grade: 2,
  },
  {
    id: 133,
    kanji: "	間	",
    meaning: "	interval	",
    onYomi: "	kan, ken	",
    kunYomi: "	ma, aida	",
    grade: 2,
  },
  {
    id: 134,
    kanji: "	方	",
    meaning: "	direction	",
    onYomi: "	hō	",
    kunYomi: "	kata	",
    grade: 2,
  },
  {
    id: 135,
    kanji: "	北	",
    meaning: "	north	",
    onYomi: "	hoku	",
    kunYomi: "	kita	",
    grade: 2,
  },
  {
    id: 136,
    kanji: "	南	",
    meaning: "	south	",
    onYomi: "	nan	",
    kunYomi: "	minami	",
    grade: 2,
  },
  {
    id: 137,
    kanji: "	東	",
    meaning: "	east	",
    onYomi: "	tō	",
    kunYomi: "	higashi, azuma	",
    grade: 2,
  },
  {
    id: 138,
    kanji: "	西	",
    meaning: "	west	",
    onYomi: "	sei, sai	",
    kunYomi: "	nishi	",
    grade: 2,
  },
  {
    id: 139,
    kanji: "	遠	",
    meaning: "	far	",
    onYomi: "	en	",
    kunYomi: "	tō-i	",
    grade: 2,
  },
  {
    id: 140,
    kanji: "	近	",
    meaning: "	near	",
    onYomi: "	kin	",
    kunYomi: "	chika-i	",
    grade: 2,
  },
  {
    id: 141,
    kanji: "	前	",
    meaning: "	before	",
    onYomi: "	zen	",
    kunYomi: "	mae	",
    grade: 2,
  },
  {
    id: 142,
    kanji: "	後	",
    meaning: "	after	",
    onYomi: "	go, kō	",
    kunYomi: "	nochi, ushi-ro, ato	",
    grade: 2,
  },
  {
    id: 143,
    kanji: "	内	",
    meaning: "	inside	",
    onYomi: "	nai	",
    kunYomi: "	uchi	",
    grade: 2,
  },
  {
    id: 144,
    kanji: "	外	",
    meaning: "	outside	",
    onYomi: "	gai, ge	",
    kunYomi: "	soto, hoka, hazu-su	",
    grade: 2,
  },
  {
    id: 145,
    kanji: "	場	",
    meaning: "	place	",
    onYomi: "	jō	",
    kunYomi: "	ba	",
    grade: 2,
  },
  {
    id: 146,
    kanji: "	地	",
    meaning: "	ground	",
    onYomi: "	chi, ji	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 147,
    kanji: "	国	",
    meaning: "	country	",
    onYomi: "	koku	",
    kunYomi: "	kuni	",
    grade: 2,
  },
  {
    id: 148,
    kanji: "	園	",
    meaning: "	garden	",
    onYomi: "	en	",
    kunYomi: "	sono	",
    grade: 2,
  },
  {
    id: 149,
    kanji: "	谷	",
    meaning: "	valley	",
    onYomi: "	koku	",
    kunYomi: "	tani	",
    grade: 2,
  },
  {
    id: 150,
    kanji: "	野	",
    meaning: "	field	",
    onYomi: "	ya	",
    kunYomi: "	no	",
    grade: 2,
  },
  {
    id: 151,
    kanji: "	原	",
    meaning: "	meadow, plain	",
    onYomi: "	gen	",
    kunYomi: "	hara	",
    grade: 2,
  },
  {
    id: 152,
    kanji: "	里	",
    meaning: "	hometown	",
    onYomi: "	ri	",
    kunYomi: "	sato	",
    grade: 2,
  },
  {
    id: 153,
    kanji: "	市	",
    meaning: "	city	",
    onYomi: "	shi	",
    kunYomi: "	ichi	",
    grade: 2,
  },
  {
    id: 154,
    kanji: "	京	",
    meaning: "	capital	",
    onYomi: "	kyō, kei	",
    kunYomi: "	miyako	",
    grade: 2,
  },
  {
    id: 155,
    kanji: "	風	",
    meaning: "	wind, -style	",
    onYomi: "	fū	",
    kunYomi: "	kaze	",
    grade: 2,
  },
  {
    id: 156,
    kanji: "	雪	",
    meaning: "	snow	",
    onYomi: "	setsu	",
    kunYomi: "	yuki	",
    grade: 2,
  },
  {
    id: 157,
    kanji: "	雲	",
    meaning: "	cloud	",
    onYomi: "	un	",
    kunYomi: "	kumo	",
    grade: 2,
  },
  {
    id: 158,
    kanji: "	池	",
    meaning: "	pond	",
    onYomi: "	chi	",
    kunYomi: "	ike	",
    grade: 2,
  },
  {
    id: 159,
    kanji: "	海	",
    meaning: "	sea	",
    onYomi: "	kai	",
    kunYomi: "	umi	",
    grade: 2,
  },
  {
    id: 160,
    kanji: "	岩	",
    meaning: "	rock	",
    onYomi: "	gan	",
    kunYomi: "	iwa	",
    grade: 2,
  },
  {
    id: 161,
    kanji: "	星	",
    meaning: "	star	",
    onYomi: "	sei	",
    kunYomi: "	hoshi	",
    grade: 2,
  },
  {
    id: 162,
    kanji: "	室	",
    meaning: "	room	",
    onYomi: "	shitsu	",
    kunYomi: "	muro	",
    grade: 2,
  },
  {
    id: 163,
    kanji: "	戸	",
    meaning: "	door	",
    onYomi: "	ko	",
    kunYomi: "	to, be	",
    grade: 2,
  },
  {
    id: 164,
    kanji: "	家	",
    meaning: "	house	",
    onYomi: "	ka, ke	",
    kunYomi: "	ie	",
    grade: 2,
  },
  {
    id: 165,
    kanji: "	寺	",
    meaning: "	Buddhist temple	",
    onYomi: "	ji	",
    kunYomi: "	tera	",
    grade: 2,
  },
  {
    id: 166,
    kanji: "	通	",
    meaning: "	pass through, commute	",
    onYomi: "	tsū	",
    kunYomi: "	tō-ru, kayo-u	",
    grade: 2,
  },
  {
    id: 167,
    kanji: "	門	",
    meaning: "	gates	",
    onYomi: "	mon	",
    kunYomi: "	kado	",
    grade: 2,
  },
  {
    id: 168,
    kanji: "	道	",
    meaning: "	road	",
    onYomi: "	dō	",
    kunYomi: "	michi	",
    grade: 2,
  },
  {
    id: 169,
    kanji: "	話	",
    meaning: "	talk	",
    onYomi: "	wa	",
    kunYomi: "	hanashi, hana-su	",
    grade: 2,
  },
  {
    id: 170,
    kanji: "	言	",
    meaning: "	say	",
    onYomi: "	gen, gon	",
    kunYomi: "	i-u, koto	",
    grade: 2,
  },
  {
    id: 171,
    kanji: "	答	",
    meaning: "	answer	",
    onYomi: "	tō	",
    kunYomi: "	kota-eru	",
    grade: 2,
  },
  {
    id: 172,
    kanji: "	声	",
    meaning: "	voice	",
    onYomi: "	sei	",
    kunYomi: "	koe	",
    grade: 2,
  },
  {
    id: 173,
    kanji: "	聞	",
    meaning: "	hear, listen, ask	",
    onYomi: "	bun, mon	",
    kunYomi: "	ki-ku	",
    grade: 2,
  },
  {
    id: 174,
    kanji: "	語	",
    meaning: "	language	",
    onYomi: "	go	",
    kunYomi: "	kata-ru	",
    grade: 2,
  },
  {
    id: 175,
    kanji: "	読	",
    meaning: "	read	",
    onYomi: "	doku	",
    kunYomi: "	yo-mu	",
    grade: 2,
  },
  {
    id: 176,
    kanji: "	書	",
    meaning: "	write	",
    onYomi: "	sho	",
    kunYomi: "	ka-ku	",
    grade: 2,
  },
  {
    id: 177,
    kanji: "	記	",
    meaning: "	record	",
    onYomi: "	ki	",
    kunYomi: "	shiru-su	",
    grade: 2,
  },
  {
    id: 178,
    kanji: "	紙	",
    meaning: "	paper	",
    onYomi: "	shi	",
    kunYomi: "	kami	",
    grade: 2,
  },
  {
    id: 179,
    kanji: "	画	",
    meaning: "	brush stroke	",
    onYomi: "	ga, kaku	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 180,
    kanji: "	絵	",
    meaning: "	picture	",
    onYomi: "	kai, e	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 181,
    kanji: "	図	",
    meaning: "	drawing	",
    onYomi: "	zu	",
    kunYomi: "	haka-ru	",
    grade: 2,
  },
  {
    id: 182,
    kanji: "	工	",
    meaning: "	craft	",
    onYomi: "	kō, ku	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 183,
    kanji: "	教	",
    meaning: "	teach	",
    onYomi: "	kyō	",
    kunYomi: "	oshi-eru	",
    grade: 2,
  },
  {
    id: 184,
    kanji: "	晴	",
    meaning: "	clear	",
    onYomi: "	sei	",
    kunYomi: "	hare	",
    grade: 2,
  },
  {
    id: 185,
    kanji: "	思	",
    meaning: "	think	",
    onYomi: "	shi	",
    kunYomi: "	omo-u	",
    grade: 2,
  },
  {
    id: 186,
    kanji: "	考	",
    meaning: "	consider	",
    onYomi: "	kō	",
    kunYomi: "	kanga-eru	",
    grade: 2,
  },
  {
    id: 187,
    kanji: "	知	",
    meaning: "	know	",
    onYomi: "	chi	",
    kunYomi: "	shi-ru	",
    grade: 2,
  },
  {
    id: 188,
    kanji: "	才	",
    meaning: "	age, ability	",
    onYomi: "	sai, zai	",
    kunYomi: "	wazukani, zae	",
    grade: 2,
  },
  {
    id: 189,
    kanji: "	理	",
    meaning: "	reason	",
    onYomi: "	ri	",
    kunYomi: "	kotowari	",
    grade: 2,
  },
  {
    id: 190,
    kanji: "	算	",
    meaning: "	calculate	",
    onYomi: "	san	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 191,
    kanji: "	作	",
    meaning: "	make	",
    onYomi: "	saku	",
    kunYomi: "	tsuku-ru	",
    grade: 2,
  },
  {
    id: 192,
    kanji: "	元	",
    meaning: "	origin	",
    onYomi: "	gen, gan	",
    kunYomi: "	moto	",
    grade: 2,
  },
  {
    id: 193,
    kanji: "	食	",
    meaning: "	eat	",
    onYomi: "	shoku	",
    kunYomi: "	ta-beru, ku-u	",
    grade: 2,
  },
  {
    id: 194,
    kanji: "	肉	",
    meaning: "	meat	",
    onYomi: "	niku	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 195,
    kanji: "	馬	",
    meaning: "	horse	",
    onYomi: "	ba	",
    kunYomi: "	uma, ma	",
    grade: 2,
  },
  {
    id: 196,
    kanji: "	牛	",
    meaning: "	cow	",
    onYomi: "	gyū	",
    kunYomi: "	ushi	",
    grade: 2,
  },
  {
    id: 197,
    kanji: "	魚	",
    meaning: "	fish	",
    onYomi: "	gyo	",
    kunYomi: "	sakana	",
    grade: 2,
  },
  {
    id: 198,
    kanji: "	鳥	",
    meaning: "	bird	",
    onYomi: "	chō	",
    kunYomi: "	tori	",
    grade: 2,
  },
  {
    id: 199,
    kanji: "	羽	",
    meaning: "	feather	",
    onYomi: "	u	",
    kunYomi: "	ha, hane	",
    grade: 2,
  },
  {
    id: 200,
    kanji: "	鳴	",
    meaning: "	chirp	",
    onYomi: "	mei	",
    kunYomi: "	na-ku	",
    grade: 2,
  },
  {
    id: 201,
    kanji: "	麦	",
    meaning: "	wheat	",
    onYomi: "	baku	",
    kunYomi: "	mugi	",
    grade: 2,
  },
  {
    id: 202,
    kanji: "	米	",
    meaning: "	rice	",
    onYomi: "	bei, mai	",
    kunYomi: "	kome	",
    grade: 2,
  },
  {
    id: 203,
    kanji: "	茶	",
    meaning: "	tea	",
    onYomi: "	cha, sa	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 204,
    kanji: "	色	",
    meaning: "	colour	",
    onYomi: "	shoku	",
    kunYomi: "	iro	",
    grade: 2,
  },
  {
    id: 205,
    kanji: "	黄	",
    meaning: "	yellow	",
    onYomi: "	ō	",
    kunYomi: "	ki	",
    grade: 2,
  },
  {
    id: 206,
    kanji: "	黒	",
    meaning: "	black	",
    onYomi: "	koku	",
    kunYomi: "	kuro	",
    grade: 2,
  },
  {
    id: 207,
    kanji: "	来	",
    meaning: "	come	",
    onYomi: "	rai	",
    kunYomi: "	ku-ru	",
    grade: 2,
  },
  {
    id: 208,
    kanji: "	行	",
    meaning: "	go	",
    onYomi: "	kō, gyō	",
    kunYomi: "	i-ku, yu-ku, okona-u	",
    grade: 2,
  },
  {
    id: 209,
    kanji: "	帰	",
    meaning: "	return	",
    onYomi: "	ki	",
    kunYomi: "	kae-ru	",
    grade: 2,
  },
  {
    id: 210,
    kanji: "	歩	",
    meaning: "	walk	",
    onYomi: "	ho, fu, bu	",
    kunYomi: "	aru-ku, ayu-mu	",
    grade: 2,
  },
  {
    id: 211,
    kanji: "	走	",
    meaning: "	run	",
    onYomi: "	sō	",
    kunYomi: "	hashi-ru	",
    grade: 2,
  },
  {
    id: 212,
    kanji: "	止	",
    meaning: "	stop	",
    onYomi: "	shi	",
    kunYomi: "	to-maru	",
    grade: 2,
  },
  {
    id: 213,
    kanji: "	活	",
    meaning: "	active	",
    onYomi: "	katsu	",
    kunYomi: "	i-kiru	",
    grade: 2,
  },
  {
    id: 214,
    kanji: "	店	",
    meaning: "	store	",
    onYomi: "	ten	",
    kunYomi: "	mise	",
    grade: 2,
  },
  {
    id: 215,
    kanji: "	買	",
    meaning: "	buy	",
    onYomi: "	bai	",
    kunYomi: "	ka-u	",
    grade: 2,
  },
  {
    id: 216,
    kanji: "	売	",
    meaning: "	sell	",
    onYomi: "	bai	",
    kunYomi: "	u-ru	",
    grade: 2,
  },
  {
    id: 217,
    kanji: "	午	",
    meaning: "	noon	",
    onYomi: "	go	",
    kunYomi: "	uma	",
    grade: 2,
  },
  {
    id: 218,
    kanji: "	汽	",
    meaning: "	steam	",
    onYomi: "	ki	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 219,
    kanji: "	弓	",
    meaning: "	bow	",
    onYomi: "	kyū	",
    kunYomi: "	yumi	",
    grade: 2,
  },
  {
    id: 220,
    kanji: "	回	",
    meaning: "	number of times, revolve	",
    onYomi: "	kai	",
    kunYomi: "	mawa-ru	",
    grade: 2,
  },
  {
    id: 221,
    kanji: "	会	",
    meaning: "	meet	",
    onYomi: "	kai, e	",
    kunYomi: "	a-u	",
    grade: 2,
  },
  {
    id: 222,
    kanji: "	組	",
    meaning: "	team	",
    onYomi: "	so	",
    kunYomi: "	kumi	",
    grade: 2,
  },
  {
    id: 223,
    kanji: "	船	",
    meaning: "	ship	",
    onYomi: "	sen	",
    kunYomi: "	fune	",
    grade: 2,
  },
  {
    id: 224,
    kanji: "	明	",
    meaning: "	bright	",
    onYomi: "	mei	",
    kunYomi: "	aka-rui	",
    grade: 2,
  },
  {
    id: 225,
    kanji: "	社	",
    meaning: "	company	",
    onYomi: "	sha	",
    kunYomi: "	yashiro	",
    grade: 2,
  },
  {
    id: 226,
    kanji: "	切	",
    meaning: "	cut	",
    onYomi: "	setsu	",
    kunYomi: "	ki-ru	",
    grade: 2,
  },
  {
    id: 227,
    kanji: "	電	",
    meaning: "	electricity	",
    onYomi: "	den	",
    kunYomi: "	inazuma	",
    grade: 2,
  },
  {
    id: 228,
    kanji: "	毎	",
    meaning: "	every	",
    onYomi: "	mai	",
    kunYomi: "	goto	",
    grade: 2,
  },
  {
    id: 229,
    kanji: "	合	",
    meaning: "	fit	",
    onYomi: "	gō	",
    kunYomi: "	a-u	",
    grade: 2,
  },
  {
    id: 230,
    kanji: "	当	",
    meaning: "	this, hit	",
    onYomi: "	tō	",
    kunYomi: "	a-taru	",
    grade: 2,
  },
  {
    id: 231,
    kanji: "	台	",
    meaning: "	pedestal	",
    onYomi: "	dai, tai	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 232,
    kanji: "	楽	",
    meaning: "	music, pleasure	",
    onYomi: "	gaku, raku	",
    kunYomi: "	tano-shii	",
    grade: 2,
  },
  {
    id: 233,
    kanji: "	公	",
    meaning: "	public	",
    onYomi: "	kō	",
    kunYomi: "	ōyake	",
    grade: 2,
  },
  {
    id: 234,
    kanji: "	引	",
    meaning: "	pull	",
    onYomi: "	in	",
    kunYomi: "	hi-ku	",
    grade: 2,
  },
  {
    id: 235,
    kanji: "	科	",
    meaning: "	section, grade	",
    onYomi: "	ka	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 236,
    kanji: "	歌	",
    meaning: "	song	",
    onYomi: "	ka	",
    kunYomi: "	uta	",
    grade: 2,
  },
  {
    id: 237,
    kanji: "	刀	",
    meaning: "	sword	",
    onYomi: "	tō	",
    kunYomi: "	katana	",
    grade: 2,
  },
  {
    id: 238,
    kanji: "	番	",
    meaning: "	number	",
    onYomi: "	ban	",
    kunYomi: "		",
    grade: 2,
  },
  {
    id: 239,
    kanji: "	用	",
    meaning: "	use	",
    onYomi: "	yō	",
    kunYomi: "	mochi-iru	",
    grade: 2,
  },
  {
    id: 240,
    kanji: "	何	",
    meaning: "	what	",
    onYomi: "	ka	",
    kunYomi: "	nani, nan	",
    grade: 2,
  },
];
